export const AVATAR_EFFECTS = [
  { id: 'av1', name: 'Aespa Fanlight', uri: require('../assets/avatar/frame_aespa_fanlight.png') },
  { id: 'av2', name: 'Angry', uri: require('../assets/avatar/frame_angry.png') },
  { id: 'av3', name: 'Aurora', uri: require('../assets/avatar/frame_aurora.png') },
  { id: 'av4', name: 'Black Hole', uri: require('../assets/avatar/frame_black_hole.png') },
  { id: 'av5', name: 'Bubble Tea', uri: require('../assets/avatar/frame_bubble_tea.png') },
  { id: 'av6', name: 'Candlelight', uri: require('../assets/avatar/frame_candlelight.png') },
  { id: 'av7', name: 'Cat Onesie', uri: require('../assets/avatar/frame_cat_onesie.png') },
  { id: 'av8', name: 'Cozycat', uri: require('../assets/avatar/frame_cozycat.png') },
  { id: 'av9', name: 'Head In The Clouds', uri: require('../assets/avatar/frame_head_in_the_clouds.png') },
  { id: 'av10', name: 'Witch Hat', uri: require('../assets/avatar/frame_witch_hat.png') },
];

export const BACKGROUND_EFFECTS = [
  { id: 'bg1', name: 'Crystal Elk', uri: require('../assets/background/frame_crystal_elk.png') },
  { id: 'bg2', name: 'Dandelion Duo', uri: require('../assets/background/frame_dandelion_duo.png') },
  { id: 'bg3', name: 'Defensive Shield', uri: require('../assets/background/frame_defensive_shield.png') },
  { id: 'bg4', name: 'Doodling', uri: require('../assets/background/frame_doodling.png') },
  { id: 'bg5', name: 'Fan Flourish', uri: require('../assets/background/frame_fan_flourish.png') },
  { id: 'bg6', name: 'Firecrackers', uri: require('../assets/background/frame_firecrackers.png') },
  { id: 'bg7', name: 'Fox Hat', uri: require('../assets/background/frame_fox_hat.png') },
  { id: 'bg8', name: 'Group Hug', uri: require('../assets/background/frame_group_hug.png') },
  { id: 'bg9', name: 'Head In The Clouds', uri: require('../assets/background/frame_head_in_the_clouds.png') },
  { id: 'bg10', name: 'Witch Hat', uri: require('../assets/background/frame_witch_hat.png') },
];

export const NAMEPLATE_EFFECTS = [
  { id: 'cd1', name: 'Hex Tiles', uri: require('../assets/card/frame_hex_tiles.png') },
  { id: 'cd2', name: 'Hugh The Rainbow', uri: require('../assets/card/frame_hugh_the_rainbow.png') },
  { id: 'cd3', name: 'IO Love', uri: require('../assets/card/frame_io_love.png') },
  { id: 'cd4', name: 'Lofi Girl Outfit', uri: require('../assets/card/frame_lofi_girl_outfit.png') },
  { id: 'cd5', name: 'Lotus Flower', uri: require('../assets/card/frame_lotus_flower.png') },
  { id: 'cd6', name: 'Lovestruck', uri: require('../assets/card/frame_lovestruck.png') },
  { id: 'cd7', name: 'Magiflo Girl', uri: require('../assets/card/frame_magiflo_girl.png') },
  { id: 'cd8', name: 'Mech Flora', uri: require('../assets/card/frame_mech_flora.png') },
  { id: 'cd9', name: 'Mirage', uri: require('../assets/card/frame_mirage.png') },
  { id: 'cd10', name: 'Mooncaps', uri: require('../assets/card/frame_mooncaps.png') },
  { id: 'cd11', name: 'Neon Nibbles', uri: require('../assets/card/frame_neon_nibbles.png') },
  { id: 'cd12', name: 'Owlbear Cub', uri: require('../assets/card/frame_owlbear_cub.png') },
  { id: 'cd13', name: 'Phoenix', uri: require('../assets/card/frame_phoenix.png') },
  { id: 'cd14', name: 'Playful Lofi Cat', uri: require('../assets/card/frame_playful_lofi_cat.png') },
  { id: 'cd15', name: 'Rose Bearer', uri: require('../assets/card/frame_rose_bearer.png') },
  { id: 'cd16', name: 'Shy', uri: require('../assets/card/frame_shy.png') },
  { id: 'cd17', name: 'Sleepy Chilledcow', uri: require('../assets/card/frame_sleepy_chilledcow.png') },
  { id: 'cd18', name: 'Solar Orbit', uri: require('../assets/card/frame_solar_orbit.png') },
  { id: 'cd19', name: 'Straw Hat', uri: require('../assets/card/frame_straw_hat.png') },
  { id: 'cd20', name: 'Unicorn', uri: require('../assets/card/frame_unicorn.png') },
  { id: 'cd21', name: 'Valorant Champions', uri: require('../assets/card/frame_valorant_champions_2024.png') },
  { id: 'cd22', name: 'Witch Hat', uri: require('../assets/card/frame_witch_hat.png') },
];
